name: Build and Deploy to ECS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 기본적으로 최신 버전을 사용하지만, 특정 버전이 필요할 경우 @v2 같은 버전 명시 가능

      - name: Set up Java
        uses: actions/setup-java@v2  # Java 버전 설치, 필요에 따라 이 부분도 다른 버전으로 설정 가능

      - name: Build with Gradle
        run: ./gradlew build -x test  # gradle 빌드 명령어, 프로젝트에 맞게 경로와 명령어 변경 필요

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1  # Amazon ECR 로그인 액션, 필요에 따라 다른 액션 사용 가능

      - name: Build Docker image
        run: docker build -t ${{ secrets.ECR_REPOSITORY_URI }} .  # ECR 주소와 자신의 프로젝트에 맞게 경로 수정

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ secrets.ECR_REPOSITORY_URI }}  # ECR 주소와 함께 설정한 이미지 푸시

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1  # ECS 배포 작업, 버전 및 설정 확인 후 사용
        with:
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}  # ECS 클러스터 이름 설정
          service: ${{ secrets.ECS_SERVICE_NAME }}  # ECS 서비스 이름 설정
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}  # ECS 작업 정의 설정
